# .pre-commit-config.yaml
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-merge-conflict

  -   repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.2.0
      hooks:
        -   id: conventional-pre-commit
            stages: [commit-msg] # This hook runs on the commit message itself

  -   repo: local
      hooks:
        -   id: maven-verify
            name: Maven Verify
            entry: ./mvnw verify
            language: system
            stages: [push] # This hook will only run on 'git push'
            always_run: true # Ensures it runs even if no files changed
